export const apiUrl = {
    CONFIG: "/assets/config.json",
    LOGIN: "/user/validate_login",
    REGISTRATION: "/user/register_user",
    PROFILE_SETTING: "/user/get_user_profile_settings",
    ALL_CATEGORIES: "/user/get_all_categories",
    ALL_SUB_CATEGORIES: "/user/get_all_subcategories",
    UPDATE_PROFILE_CATEGORIES: "/user/update_profile_category",
    UPDATE_PROFILE_EXPERTISE: "/user/update_profile_expertise",
    UPDATE_PROFILE_EXPERTISE_LEVEL: "/user/update_profile_expertise_level",
    UPDATE_PROFILE_EDU: "/user/add_update_profile_education",
    SKIP_THIS_STEP: "/user/skip_this_step",
    DELETE_EDU: "/user/delete_education",
    EDU_DETAILS: "/user/get_education_details",
    DELETE_EMP: "/user/delete_employment",
    ALL_SKILLS: "/user/get_skills",
    EMP_DETAILS: "/user/get_employment_details",
    GET_COUNTRIES: "/user/get_countries",
    GET_STATES: "/user/get_states",
    GET_CITIES: "/user/get_cities",
    CALLING_CODE: "/user/get_calling_code",
    UPDATE_PROFILE_EMP: "/user/add_update_profile_employment",
    UPDATE_PROFILE_LANG: "/user/add_update_profile_language",
    GET_LANG_LIST: "/user/get_language_list",
    UPDATE_PROFILE_RATE: "/user/add_update_profile_hourlyrate",
    UPDATE_PROFILE_TITLE: "/user/add_update_profile_title_overview",
    UPDATE_PROFILE_LOC: "/user/add_update_profile_location",
    UPDATE_PROFILE_PHONE: "/user/add_update_profile_phone",
    UPDATE_PROFILE_PHOTO: "/user/add_update_profile_photo",
    UPDATE_PROFILE_JOB_TYPE: "/user/update_profile_job_type",
    DELETE_PROFILE_PROJECTS: "/user/delete_project",
    GET_PROJECT_DETAILS : "/user/get_project_details",
    ADD_UPDATE_PROFILE_PROJECT : "/user/add_update_profile_project",
    DELETE_LICENSE_CERTIFICATE: "/user/delete_license_certificate",
    GET_LICENSE_CERTIFICATE_DETAILS: "/user/get_license_certificate_details",
    ADD_UPDATE_LICENSE_CERTIFICATE: "/user/add_update_license_certificate",
    UPDATE_PROFILE_JOB_LOCATION_PREFERENCE: "/user/update_profile_job_location_preference",
    UPDATE_PROFILE_TIMELINE_HIRING: "/user/update_profile_timeline_hiring",
    REMOVE_JOB_DESCRIPTION : "/user/remove_job_description",
    ALL_INDUSTRIES: "/user/get_all_industries",
    ALL_JOB_PROFILE: "/user/get_job_profile",
    FORGOT_PASSWORD : "/user/forgot_password",
    CHANGE_PASSWORD : "/user/change_password",
    VALIDATE_PASSWORD : "/user/validate_temp_password",
    ADMIN_LOGIN: "/admin/admin_validate_login",
    
}