export const apiUrl = {
    CONFIG: "/assets/config.json",
    LOGIN: "/user/validate_login",
    REGISTRATION: "/user/register_user",
    PROFILE_SETTING: "/user/get_user_profile_settings",
    ALL_CATEGORIES: "/user/get_all_categories",
    ALL_SUB_CATEGORIES: "/user/get_all_subcategories",
    UPDATE_PROFILE_CATEGORIES: "/user/update_profile_category",
    UPDATE_PROFILE_EXPERTISE: "/user/update_profile_expertise",
    UPDATE_PROFILE_EXPERTISE_LEVEL: "/user/update_profile_expertise_level",
    UPDATE_PROFILE_EDU: "/user/add_update_profile_education",
    SKIP_THIS_STEP: "/user/skip_this_step",
    DELETE_EDU: "/user/delete_education",
    EDU_DETAILS: "/user/get_education_details",
    DELETE_EMP: "/user/delete_employment",
    EMP_DETAILS: "/user/get_employment_details",
    GET_COUNTRIES: "/user/get_countries",
    CALLING_CODE: "/user/get_calling_code",
    UPDATE_PROFILE_EMP: "/user/add_update_profile_employment",
    UPDATE_PROFILE_LANG: "/user/add_update_profile_language",
    GET_LANG_LIST: "/user/get_language_list",
    UPDATE_PROFILE_RATE: "/user/add_update_profile_hourlyrate",
    UPDATE_PROFILE_TITLE: "/user/add_update_profile_title_overview",
    UPDATE_PROFILE_LOC: "/user/add_update_profile_location",
    UPDATE_PROFILE_PHONE: "/user/add_update_profile_phone"
}